[package]
name = "tmages"
version = "0.1.0"
description = "image converter offline TUI"
authors = ["Manish Acharya <contact@manishacharya.name.np>"]
license = "MIT"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
dirs = "6.0.0"
image = "0.25.8"
ratatui = "0.29.0"
